### PR TITLE
Make piped payload requests retryable

### LINKED ISSUE #258: Support streaming a file to a PUT or POST request
_Example Failure:_ 
https://github.com/cloudant/couchbackup/commit/59676c6253494485c4d73f0a019656e9bff9a670

Also see failing build, https://cloudant-sdks-jenkins.swg-devops.com:8443/blue/organizations/jenkins/couchbackup/detail/update-cloudant-version/2/pipeline.

### PR DESCRIPTION
**Pull request by smithsz**
Thanks for your hard work, please ensure all items are complete before opening.

- [x] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://github.com/cloudant/nodejs-cloudant/blob/master/DCO1.1.txt)
- [x] You have added tests for any code changes
- [x] You have updated the [CHANGES.md](https://github.com/cloudant/nodejs-cloudant/blob/master/CHANGES.md)
- [x] You have completed the PR template below:

## What
Make piped payload requests retryable.

## How
Create a new `ReplayableStream` class to capture and replay all data written.

## Testing
Includes additional unit tests.

## Issues
Fixes #258.

### CODE REVIEW

File: lib/client.js [hunk 1]
```diff
@@ -161,7 +163,7 @@ class CloudantClient {
     request.abort = false;
     request.clientCallback = callback;
 
-    request.clientStream = new PassThroughDuplex();
+    request.clientStream = new PassThroughDuplex(ReplayableStream, stream.PassThrough);
```
Comment (ricellis) [inline lib/client.js]: It might be nice to do this only if the thing is actually being piped and there are plugins configured to avoid the overheads of the `ReplayableStream` in the simplest use cases. I think that optimisation can be safely added later though.

File: test/plugins/retry5xx.js [hunk 2]
```diff
@@ -664,5 +778,77 @@ describe('Retry5xx Plugin', function() {
           done();
         });
     });
+
+    it('successfully retries request with piped payload on 500 response and returns 200 response', function(done) {
```
Comment (ricellis) [inline test/plugins/retry5xx.js]: It'd be so much nicer to have this test in a function or something instead of pasted 3 times!
I'd still rather have it pasted 3 times than no test though :)

File: test/replayablestream.js [hunk 3]
```diff
@@ -0,0 +1,72 @@
...
+// limitations under the License.
+
+/* global describe it */
+'use strict';
+
+const assert = require('assert');
+const fs = require('fs');
+const stream = require('stream');
+
+const ReplayableStream = require('../lib/replayablestream.js');
```
Comment (ricellis) [inline test/replayablestream.js]: It would be nice if Node.js provided a test for compliance to the `Stream` `Readable` and `Writeable` prototypes that we could use to test this and the PassThroughDuplex. It would help alert us to API changes on them as well. Alas I couldn't find one.
