### PR TITLE
139 fix security asymmetry

### LINKED ISSUE #139: get_security / set_security asymmetrical
`db.get_security()` seems to return the entire `_security` record as per https://cloudant.com/for-developers/faq/auth/ 

``` js
{
  "_id": "security", 
  "cloudant": {
    "exampleuser1": [
      "_reader", 
      "_writer"
    ]
  }
}
```

however, `db.set_security(x)` does a `POST` to `_security`  with `{ cloudant: x }` 

so, if i'm trying to add user permissions for something, I can't do  `get_security()`, mutate the value with `x.user=['_reader']`, and just call `set_security(x)`. I end up with extra `cloudant: {}` objects in the security record that way.

### PR DESCRIPTION
**Pull request by smithsz**
Thanks for your hard work, please ensure all items are complete before opening.

- [x] Tick to sign-off your agreement to the [Developer Certificate of Origin (DCO) 1.1](https://github.com/cloudant/nodejs-cloudant/blob/master/DCO1.1.txt)
- [x] You have added tests for any code changes
- [x] You have updated the [CHANGES.md](https://github.com/cloudant/nodejs-cloudant/blob/master/CHANGES.md)
- [x] You have completed the PR template below:

## What
Fix `get_security`/`set_security` asymmetry.

## Testing
Updates unit tests.

## Issues
Fixes #139.

### CODE REVIEW

File: cloudant.js [hunk 1]
```diff
@@ -92,9 +92,11 @@ function Cloudant(options, callback) {
    // https://console.bluemix.net/docs/services/Cloudant/api/authorization.html#modifying-permissions
     var set_security = function(permissions, callback) { // eslint-disable-line camelcase
       var path = '_api/v2/db/' + encodeURIComponent(db) + '/_security';
-      return nano.request({ path: path,
+      return nano.request({
+        path: path,
         method: 'put',
-        body: {cloudant: permissions} }, callback);
```
Comment (ricellis) [inline cloudant.js]: Is it worth doing something like this so people can get it right either way:
```js
if permissions.cloudant {
  body = permissions
} else {
  body = {cloudant: permissions}
}
```

I'm not sure we should add the complexity given that the doc makes it clear what kind of object is required, but am just thinking "aloud".

Comment (smithsz) [reply cloudant.js]: Unsure. Would this still work with `couchdb_auth_only`? You'd need to specify a `cloudant` key I guess.
